# Generated by Django 3.0.7 on 2020-08-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=25, verbose_name='Username')),
                ('fname', models.CharField(max_length=25, verbose_name='First Name')),
                ('lname', models.CharField(max_length=25, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('password1', models.CharField(max_length=100, verbose_name='Password')),
                ('password2', models.CharField(max_length=100, verbose_name='Confirm Password')),
            ],
        ),
        migrations.CreateModel(
            name='Setupmodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usermodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(max_length=30)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
