# Generated by Django 3.0.7 on 2020-08-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='fname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='lname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userid',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
