# Generated by Django 3.0.7 on 2020-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200815_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='mobile',
            field=models.IntegerField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
