# Generated by Django 3.0.7 on 2020-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200816_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='mobile',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
