# Generated by Django 3.0.7 on 2020-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobileformat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=1)),
                ('second', models.CharField(max_length=1)),
                ('third', models.CharField(max_length=1)),
                ('fourth', models.CharField(max_length=1)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='newuser',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
