# Generated by Django 3.0.7 on 2020-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200823_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileformat',
            name='first',
        ),
        migrations.RemoveField(
            model_name='mobileformat',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='mobileformat',
            name='second',
        ),
        migrations.RemoveField(
            model_name='mobileformat',
            name='third',
        ),
        migrations.AddField(
            model_name='mobileformat',
            name='format',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileformat',
            name='provider',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
