# Generated by Django 3.0.7 on 2020-08-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200823_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=4)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mobileformat',
            old_name='format',
            new_name='mformat',
        ),
        migrations.AlterField(
            model_name='mobileformat',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Serviceprovider'),
        ),
    ]
