# Generated by Django 3.0.7 on 2020-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200823_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileformat',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='mobile',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
