# Generated by Django 3.0.7 on 2020-08-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200829_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileformat',
            name='length',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='mobileformat',
            name='mformat',
            field=models.CharField(max_length=10),
        ),
    ]
