# Generated by Django 3.0.7 on 2020-08-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30, unique=True, verbose_name='Staff Position')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staffmodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpic', models.ImageField(default='profile/profile.jpg', upload_to='profile', verbose_name='User Photo')),
                ('staff', models.IntegerField(default=0)),
                ('level', models.IntegerField()),
                ('description', models.CharField(max_length=30, null=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Staff Title')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsnumber', models.IntegerField(null=True, unique=True, verbose_name='TS Number')),
                ('fname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('mname', models.CharField(blank=True, max_length=20, verbose_name='Middle Name')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('isconfirmed', models.BooleanField(default=False)),
                ('empnumber', models.IntegerField(null=True, unique=True, verbose_name='Employee No.')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Contact No.')),
                ('nrc', models.CharField(max_length=11, null=True, verbose_name='NRC')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of Bireth')),
                ('first_appointment', models.DateField(null=True, verbose_name='Date of First Appointment')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('search', models.CharField(max_length=200, null=True, verbose_name='Search')),
                ('export_to_file', models.BooleanField(default=False)),
                ('qualifications', models.IntegerField(default=0)),
                ('profilepic', models.ImageField(default='profile/profile.jpg', upload_to='profile', verbose_name='Staff Photo')),
                ('is_updated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.District')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Position')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Province')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Provincialstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('mname', models.CharField(blank=True, max_length=20, verbose_name='Middle Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('isconfirmed', models.BooleanField(default=False)),
                ('empnumber', models.IntegerField(verbose_name='Employee No.')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Contact No.')),
                ('nrc', models.CharField(max_length=11, null=True, verbose_name='NRC')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of Bireth')),
                ('first_appointment', models.DateField(null=True, verbose_name='Date of First Appointment')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('search', models.CharField(max_length=200, null=True, verbose_name='Search')),
                ('export_to_file', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('profilepic', models.ImageField(default='profile/profile.jpg', upload_to='profile', verbose_name='Staff Photo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Position')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Province')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Districtstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('mname', models.CharField(blank=True, max_length=20, verbose_name='Middle Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('isconfirmed', models.BooleanField(default=False)),
                ('empnumber', models.IntegerField(verbose_name='Employee No.')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Contact No.')),
                ('nrc', models.CharField(max_length=11, null=True, verbose_name='NRC')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of Bireth')),
                ('first_appointment', models.DateField(null=True, verbose_name='Date of First Appointment')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('search', models.CharField(max_length=200, null=True, verbose_name='Search')),
                ('export_to_file', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('profilepic', models.ImageField(default='profile/profile.jpg', upload_to='profile', verbose_name='Staff Photo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.District')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Position')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Province')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Title')),
            ],
        ),
    ]
