# Generated by Django 3.0.7 on 2020-08-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Registred', 'Registred'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Registred', max_length=11, verbose_name='STATUS'),
        ),
    ]
