# Generated by Django 3.0.7 on 2020-08-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='comment',
            field=models.CharField(default='-', max_length=200, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Registred', 'Registered'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Registered', max_length=11, verbose_name='STATUS'),
        ),
    ]
