# Generated by Django 3.0.7 on 2020-08-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200817_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtstaff',
            name='empnumber',
            field=models.IntegerField(null=True, unique=True, verbose_name='Employee No.'),
        ),
        migrations.AlterField(
            model_name='provincialstaff',
            name='empnumber',
            field=models.IntegerField(null=True, unique=True, verbose_name='Employee No.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='comment',
            field=models.CharField(default=' ', max_length=200, verbose_name='Comment'),
        ),
    ]
