# Generated by Django 3.0.7 on 2020-08-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200819_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtstaff',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Position'),
        ),
        migrations.AlterField(
            model_name='provincialstaff',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Position'),
        ),
    ]
