# Generated by Django 3.0.7 on 2020-08-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200819_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtstaff',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Title'),
        ),
        migrations.AlterField(
            model_name='provincialstaff',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Title'),
        ),
    ]
