# Generated by Django 3.0.7 on 2020-08-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200819_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtstaff',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='provincialstaff',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
