# Generated by Django 3.0.7 on 2020-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20200823_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtstaff',
            name='empnumber',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Employee No.'),
        ),
        migrations.AlterField(
            model_name='provincialstaff',
            name='empnumber',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Employee No.'),
        ),
    ]
