# Generated by Django 3.0.7 on 2020-08-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20200823_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtstaff',
            name='status',
            field=models.CharField(choices=[('Registred', 'Registered'), ('Updated', 'Updated')], default='Registered', max_length=11, verbose_name='STATUS'),
        ),
        migrations.AddField(
            model_name='provincialstaff',
            name='status',
            field=models.CharField(choices=[('Registred', 'Registered'), ('Updated', 'Updated')], default='Registered', max_length=11, verbose_name='STATUS'),
        ),
    ]
