# Generated by Django 3.0.7 on 2020-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20200828_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtstaff',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Contact No.'),
        ),
        migrations.AlterField(
            model_name='provincialstaff',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Contact No.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Contact No.'),
        ),
    ]
