# Generated by Django 3.1.2 on 2021-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20200903_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Pending', 'Pending'), ('Updated', 'Updated'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Registered', max_length=11, verbose_name='STATUS'),
        ),
    ]
