# Generated by Django 3.0.7 on 2020-08-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='staffnumber',
            field=models.IntegerField(default=0),
        ),
    ]
