# Generated by Django 3.1.2 on 2021-03-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_district_staffnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='export_to_file',
            field=models.BooleanField(default=False),
        ),
    ]
