# Generated by Django 3.0.7 on 2020-08-20 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0007_auto_20200820_2133'),
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maindocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docttype', models.CharField(max_length=100, verbose_name='Document Type')),
                ('description', models.CharField(default='', max_length=100)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Uploaded', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Staffdocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentupload', models.FileField(upload_to='uploads', verbose_name='Upload Document')),
                ('isimage', models.BooleanField(default=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qualification.Maindocument')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Staff')),
            ],
        ),
    ]
