# Generated by Django 3.0.7 on 2020-08-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0002_auto_20200820_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdocument',
            name='docname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
