# Generated by Django 3.0.7 on 2020-08-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0003_staffdocument_docname'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindocument',
            name='documents',
            field=models.IntegerField(default=0),
        ),
    ]
