# Generated by Django 3.0.7 on 2020-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0004_maindocument_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdocument',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Uploaded', max_length=10, verbose_name='Status'),
        ),
    ]
