# Generated by Django 3.0.7 on 2020-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0005_staffdocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
