# Generated by Django 3.0.7 on 2020-09-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0006_maindocument_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
