# Generated by Django 3.0.7 on 2020-09-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0007_documentupload_is_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentupload',
            name='is_uploaded',
        ),
        migrations.AddField(
            model_name='qualification',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
