# Generated by Django 3.0.7 on 2020-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0008_auto_20200903_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdocument',
            name='is_uploaded',
            field=models.BooleanField(default=True),
        ),
    ]
